# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto import messages_pb2 as shared_dot_proto_dot_messages__pb2
from shared.proto import services_pb2 as shared_dot_proto_dot_services__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shared/proto/services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """QueueService manages async event coordination
    Pattern: Asynchronous Coordination (see docs/patterns/edge-cloud-deployment/async-coordination.md)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueEvent = channel.unary_unary(
                '/analytics.QueueService/EnqueueEvent',
                request_serializer=shared_dot_proto_dot_messages__pb2.Event.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.DequeueBatch = channel.unary_unary(
                '/analytics.QueueService/DequeueBatch',
                request_serializer=shared_dot_proto_dot_services__pb2.DequeueBatchRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.EventBatch.FromString,
                _registered_method=True)
        self.AckBatch = channel.unary_unary(
                '/analytics.QueueService/AckBatch',
                request_serializer=shared_dot_proto_dot_services__pb2.AckBatchRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.AckBatchResponse.FromString,
                _registered_method=True)
        self.GetQueueStatus = channel.unary_unary(
                '/analytics.QueueService/GetQueueStatus',
                request_serializer=shared_dot_proto_dot_services__pb2.GetQueueStatusRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.QueueStatus.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """QueueService manages async event coordination
    Pattern: Asynchronous Coordination (see docs/patterns/edge-cloud-deployment/async-coordination.md)
    """

    def EnqueueEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DequeueBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueEvent,
                    request_deserializer=shared_dot_proto_dot_messages__pb2.Event.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.EnqueueResponse.SerializeToString,
            ),
            'DequeueBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueBatch,
                    request_deserializer=shared_dot_proto_dot_services__pb2.DequeueBatchRequest.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.EventBatch.SerializeToString,
            ),
            'AckBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AckBatch,
                    request_deserializer=shared_dot_proto_dot_services__pb2.AckBatchRequest.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.AckBatchResponse.SerializeToString,
            ),
            'GetQueueStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStatus,
                    request_deserializer=shared_dot_proto_dot_services__pb2.GetQueueStatusRequest.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.QueueStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """QueueService manages async event coordination
    Pattern: Asynchronous Coordination (see docs/patterns/edge-cloud-deployment/async-coordination.md)
    """

    @staticmethod
    def EnqueueEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.QueueService/EnqueueEvent',
            shared_dot_proto_dot_messages__pb2.Event.SerializeToString,
            shared_dot_proto_dot_services__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DequeueBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.QueueService/DequeueBatch',
            shared_dot_proto_dot_services__pb2.DequeueBatchRequest.SerializeToString,
            shared_dot_proto_dot_services__pb2.EventBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.QueueService/AckBatch',
            shared_dot_proto_dot_services__pb2.AckBatchRequest.SerializeToString,
            shared_dot_proto_dot_services__pb2.AckBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.QueueService/GetQueueStatus',
            shared_dot_proto_dot_services__pb2.GetQueueStatusRequest.SerializeToString,
            shared_dot_proto_dot_services__pb2.QueueStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObservabilityServiceStub(object):
    """ObservabilityService manages tracing and metrics
    Pattern: Distributed Tracing (see docs/patterns/observability/distributed-tracing.md)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordSpan = channel.unary_unary(
                '/analytics.ObservabilityService/RecordSpan',
                request_serializer=shared_dot_proto_dot_services__pb2.Span.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.RecordSpanResponse.FromString,
                _registered_method=True)
        self.GetTrace = channel.unary_unary(
                '/analytics.ObservabilityService/GetTrace',
                request_serializer=shared_dot_proto_dot_services__pb2.GetTraceRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.Trace.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/analytics.ObservabilityService/GetMetrics',
                request_serializer=shared_dot_proto_dot_services__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_services__pb2.MetricsResponse.FromString,
                _registered_method=True)


class ObservabilityServiceServicer(object):
    """ObservabilityService manages tracing and metrics
    Pattern: Distributed Tracing (see docs/patterns/observability/distributed-tracing.md)
    """

    def RecordSpan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordSpan,
                    request_deserializer=shared_dot_proto_dot_services__pb2.Span.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.RecordSpanResponse.SerializeToString,
            ),
            'GetTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=shared_dot_proto_dot_services__pb2.GetTraceRequest.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.Trace.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=shared_dot_proto_dot_services__pb2.GetMetricsRequest.FromString,
                    response_serializer=shared_dot_proto_dot_services__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.ObservabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.ObservabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservabilityService(object):
    """ObservabilityService manages tracing and metrics
    Pattern: Distributed Tracing (see docs/patterns/observability/distributed-tracing.md)
    """

    @staticmethod
    def RecordSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.ObservabilityService/RecordSpan',
            shared_dot_proto_dot_services__pb2.Span.SerializeToString,
            shared_dot_proto_dot_services__pb2.RecordSpanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.ObservabilityService/GetTrace',
            shared_dot_proto_dot_services__pb2.GetTraceRequest.SerializeToString,
            shared_dot_proto_dot_services__pb2.Trace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.ObservabilityService/GetMetrics',
            shared_dot_proto_dot_services__pb2.GetMetricsRequest.SerializeToString,
            shared_dot_proto_dot_services__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
